name: ci-auto-fix

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-and-fix:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Boot iOS Simulator
        shell: bash
        run: |
          xcrun simctl bootstatus "iPhone 15" -b || (
            xcrun simctl boot "iPhone 15" || true
            xcrun simctl bootstatus "iPhone 15" -b
          )

      - name: "Auto loop: build/test -> fix -> retest (max 3 rounds)"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        shell: bash
        run: |
          set -e
          rounds=0
          max=3
          pass=1
          while [ $rounds -lt $max ]; do
            echo "=== Round $((rounds+1))/$max: make test ==="
            set +e
            make test | tee test_output.txt
            code=$?
            set -e
            if [ $code -eq 0 ]; then
              echo "✅ Tests passed."
              pass=0
              break
            fi
            echo "❌ Tests failed. Ask LLM to produce minimal fixes..."
            python3 .github/scripts/fix_tests.py
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: auto-fix from LLM (round $((rounds+1)))" || true
            git push || true
            rounds=$((rounds+1))
          done
          exit $pass
