name: ci-auto-fix

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-and-fix:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app
          xcodebuild -version
          xcrun --version

      - name: Install XcodeGen & generate project
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: |
          brew install xcodegen
          xcodegen --version
          xcodegen generate

      - name: Pick & boot an available iPhone simulator
        id: sim
        shell: bash
        run: |
          set -euo pipefail

          UDID="$(xcrun simctl list devices available --json | /usr/bin/python3 - <<'PY'
import sys, json
d=json.load(sys.stdin)
devs=[dev for arr in d.get("devices",{}).values() for dev in arr if dev.get("isAvailable")]
print(devs[0]["udid"] if devs else "")
PY
)"
          if [[ -z "${UDID}" ]]; then
            echo "No available simulator. Creating one…"

            RUNTIME="$(xcrun simctl list runtimes --json | /usr/bin/python3 - <<'PY'
import sys, json
rts=json.load(sys.stdin).get("runtimes",[])
ios=[r for r in rts if r.get("platform")=="iOS" and r.get("isAvailable", True)]
ios=sorted(ios, key=lambda x: x.get("version","0"), reverse=True)
print(ios[0]["identifier"] if ios else "")
PY
)"
            if [[ -z "${RUNTIME}" ]]; then
              echo "❌ No available iOS runtime in the selected Xcode."
              xcrun simctl list runtimes
              exit 1
            fi

            DEVICETYPE="$(xcrun simctl list devicetypes | grep -E "iPhone (15|14|13|SE)" | head -n1 | sed -E 's/.*\((.*)\).*/\1/')"
            if [[ -z "${DEVICETYPE}" ]]; then
              DEVICETYPE="$(xcrun simctl list devicetypes | grep -E "iPhone" | head -n1 | sed -E 's/.*\((.*)\).*/\1/')"
            fi

            if [[ -z "${DEVICETYPE}" ]]; then
              echo "❌ No iPhone device type found:"
              xcrun simctl list devicetypes
              exit 1
            fi

            UDID="$(xcrun simctl create "CI-iPhone" "${DEVICETYPE}" "${RUNTIME}")"
          fi

          xcrun simctl boot "${UDID}" || true
          xcrun simctl bootstatus "${UDID}" -b
          echo "SIMULATOR_UDID=${UDID}" | tee -a "$GITHUB_ENV"
          echo "✅ Using simulator: ${UDID}"
          xcrun simctl list devices | sed -n '1,80p'

      - name: Auto loop: build/test -> fix -> retest (max 3 rounds)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        shell: bash
        run: |
          set -e
          rounds=0
          max=3
          pass=1
          while [ $rounds -lt $max ]; do
            echo "=== Round $((rounds+1))/$max: make test ==="
            make test DEST="platform=iOS Simulator,id=${SIMULATOR_UDID}" | tee test_output.txt
            code=$?
            set -e
            if [ $code -eq 0 ]; then
              echo "✅ Tests passed."
              pass=0
              break
            fi

            echo "❌ Tests failed. Ask LLM to produce minimal fixes..."
            python3 .github/scripts/fix_tests.py

            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: auto-fix from LLM (round $((rounds+1)))" || true
            git push || true

            rounds=$((rounds+1))
          done
          exit $pass
