name: ci-auto-fix

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-and-fix:
    runs-on: macos-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # （可按需改成你機器上的版本路徑，例如 /Applications/Xcode_16.4.app）
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      # 以 project.yml 生成 .xcodeproj，避免手寫 pbxproj 壞檔
      - name: Install XcodeGen & generate project
        run: |
          brew install xcodegen
          xcodegen generate

      # 揀一個可用嘅 iPhone 模擬器，並確保開機
      - name: Pick & boot an available iPhone simulator
        id: pick-sim
        shell: bash
        run: |
          set -euo pipefail

          # 揀第一個可用嘅 iPhone（Booted/Shutdown 任一）
          udid=$(xcrun simctl list devices available | awk -F '[()]' '/iPhone .* (Shutdown|Booted)/{print $2; exit}')
          if [ -z "${udid:-}" ]; then
            echo "No available iPhone simulator found" >&2
            exit 1
          fi

          # 如未開機就 boot，並等到 boot 完成
          if ! xcrun simctl bootstatus "$udid" >/dev/null 2>&1; then
            xcrun simctl boot "$udid" || true
            for i in {1..60}; do
              if xcrun simctl bootstatus "$udid" >/dev/null 2>&1; then break; fi
              sleep 2
